<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="diffbot" params="prefix">

    <xacro:property name="wheel_separation" value="0.45" />
    <xacro:property name="wheel_radius" value="0.005" />

    <link name="${prefix}base_footprint" />
    <!-- 기본 링크 -->
    <link name="${prefix}base_link">
        <visual>
            <geometry>
                <box size="0.5 0.5 0.1" />
            </geometry>
            <material name="blue">
                <color rgba="0 0 1 1" />
            </material>
        </visual>
    </link>
    <joint name="${prefix}base_joint" type="fixed">
        <parent link="${prefix}base_footprint" />
        <child link="${prefix}base_link" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>
    <!-- 왼쪽 바퀴 -->
    <link name="${prefix}wheel_left">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="0.02" />
            </geometry>
            <material name="blue">
                <color rgba="0 0 0 1" />
            </material>
        </visual>
    </link>
    <!-- 오른쪽 바퀴 -->
    <link name="${prefix}wheel_right">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="0.02" />
            </geometry>
            <material name="blue">
                <color rgba="0 0 0 1" />
            </material>
        </visual>
    </link>
    <!-- 왼쪽 바퀴 조인트 -->
    <joint name="${prefix}base_to_wheel_left" type="continuous">
        <parent link="${prefix}base_link" />
        <child link="${prefix}wheel_left" />
        <origin xyz="0 -${wheel_separation / 2} 0.3" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>
    <!-- 오른쪽 바퀴 조인트 -->
    <joint name="${prefix}base_to_wheel_right" type="continuous">
        <parent link="${prefix}base_link" />
        <child link="${prefix}wheel_right" />
        <origin xyz="0 ${wheel_separation / 2} 0.3" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>
    <link name="${prefix}base_scan">
        <visual>
            <origin xyz="0 0 -0.046" rpy="0 0 0" />
            <geometry>
                <box size="0.052 0.052 0.03" />
            </geometry>
            <material name="blue" />
        </visual>
    </link>
    <joint name="${prefix}scan_joint" type="fixed">
        <parent link="${prefix}base_link" />
        <child link="${prefix}base_scan" />
        <origin xyz="0.46 0.225 0.28" rpy="0 0 0" />
    </joint>
  </xacro:macro>
</robot>