<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="diff_drive_robot">
  <!-- 매크로 정의 -->
  <xacro:property name="wheel_separation" value="0.45"/>
  <xacro:property name="wheel_radius" value="0.01"/>
  <!-- 기본 링크 -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="0.5 0.5 0.1"/>
      </geometry>
      <material name="blue">
        <color rgba="0 0 1 1"/>
      </material>
    </visual>
  </link>
  <!-- 왼쪽 바퀴 -->
  <link name="wheel_left">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="0.02"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
  </link>
  <!-- 오른쪽 바퀴 -->
  <link name="wheel_right">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="0.02"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
  </link>
  <!-- 왼쪽 바퀴 조인트 -->
  <joint name="base_to_wheel_left" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_left"/>
    <origin xyz="-${wheel_separation / 2} 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>
  <!-- 오른쪽 바퀴 조인트 -->
  <joint name="base_to_wheel_right" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_right"/>
    <origin xyz="${wheel_separation / 2} 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>
</robot>
